---

- name: Install bash
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
  tags: packages

- name: Install packages via apt
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - git
    - build-essential
    - python-dev
    - python-pip
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline6-dev
    - libdb5.1-dev
    - libgdbm-dev
    - libsqlite3-dev
    - libssl-dev
    - libbz2-dev
    - libexpat1-dev
    - liblzma-dev
    - zlib1g-dev
    - flex bison
    - bison
    - libreadline6-dev
    - zlib1g-dev
    - libossp-uuid-dev
    - wget ca-certificates
    - vim
    - postgresql-9.3
    - postgresql-contrib
    - postgresql-9.3-postgis-2.1
    - postgresql-9.3-postgis-scripts
    - libpq-dev
  tags: packages

- name: Set django_settings module
  lineinfile: dest=/home/vagrant/.bashrc line='export DJANGO_SETTINGS_MODULE="es.settings.local_dev"'

- name: Alias to activate virtualenv
  lineinfile: dest=/home/vagrant/.bashrc line='alias esenv="source /home/vagrant/venv/bin/activate"'

