# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spending', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('rate', models.CharField(choices=[('annually', 'Anually'), ('bimonthly', 'Bi-Monthly'), ('monthly', 'Monthly'), ('daily', 'Daily')], max_length=65)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spending.Category')),
            ],
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='logs',
            field=models.ManyToManyField(to='budget.BudgetLog'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
