# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(blank=True, to='spending.Category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.ManyToManyField(blank=True, to='spending.Note'),
        ),
    ]
